//$(`${'<a id="iraq" href=""><i class="fa fa-refresh fa-spin fa-3x fa-fw" aria-hidden="true"></i></a><img id="asim70"src="https://www.iraqiichat.com/sico/1615772859898.jpg"style="width:100%"><div class="fm borderf" style="padding:2px;background-color: #ffffff00;"> برمجه: <a href="https://hr-iq.com/" class="fx borderf">موبايل هوست</a></div>'}`)['insertBefore']('.nav-tabs')
$('.nav-tabs')['addClass']('fl')['css']('width', '100%'), $(`${'<center><div id="iraq1" style="top: 0;">\x0D\x0A<a id="iraq7" rel="dofollow" title="القوانين" href="" style="border-radius: 0px 0 5px 5px;\x0D\x0A    border-bottom: 2px solid#f7d322;" class="fl mini  fa fa-star-half-o btn btn-primary" target="_blank"></a>\x0D\x0A<a id="iraq7" rel="dofollow" title="الاشتراكات" href="" style="border-radius: 0px 0 5px 5px;\x0D\x0A    border-bottom: 2px solid#f7d322;" class="fl mini  fa fa-star-half-o btn btn-primary" target="_blank"></a>\x0D\x0A<a id="iraq7" rel="dofollow" title="راديو" href="" style="border-radius: 0px 0 5px 5px;\x0D\x0A    border-bottom: 2px solid#f7d322;" class="fl mini  fa fa-volume-up btn btn-primary" target="_blank"></a>\x0D\x0A<a id="iraq7" rel="dofollow" title="ابراج" href="" style="border-radius: 0px 0 5px 5px;\x0D\x0A    border-bottom: 2px solid#f7d322;" class="fl mini  fa fa-fire btn btn-primary" target="_blank"></a><a id="iraq7" rel="dofollow" title="اتصل بنا" href="" style="border-radius: 0px 0 5px 5px;\x0D\x0A    border-bottom: 2px solid#f7d322;" class="fl mini fa fa-envelope btn btn-primary" target="_blank"></a>\x0D\x0A<a id="iraq7" rel="dofollow" title="قوانين السوابر" href="" style="border-radius: 0px 0 5px 5px;\x0D\x0A    border-bottom: 2px solid#f7d322;" class="fl mini fa fa-exclamation-triangle btn btn-primary" target="_blank"></a>\x0D\x0A<a id="iraq7" rel="dofollow" title="تطبيق الشات" href="" style="border-radius: 0px 0 5px 5px;\x0D\x0A    border-bottom: 2px solid#f7d322;" class="fl mini fa fa-android btn btn-primary" target="_blank"></a>\x0D\x0A<a id="iraq7" rel="dofollow" title="اختصارات الشات" href="" style="border-radius: 0px 0 5px 5px;\x0D\x0A    border-bottom: 2px solid#f7d322;" class="fl mini fa fa-tencent-weibo btn btn-primary" target="_blank"></a>\x0D\x0A</div></center>'}`)['insertBefore']('div#tlogins .lonline.light.break');
$(`${'<center><div><marquee direction="right" id="ir43" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="3"> &nbsp;أهلا وسهلا بكم في شات <font color="#595757" class="iraq12"> آحبـك </font> ● · ‫أفضل سوبر لهذا الأسبوع · ● <font class="iraq11" color="#727A54">&nbsp; قريبا ^_^ &nbsp;</font> ● · ‫أفضل زائر لهذا الأسبوع · ● <font class="iraq11" color="#ff9900">&nbsp;قـريبا&nbsp;</font> ● · ‫أفضل زائرة لهذا الأسبوع · ● <font class="iraq11" color="#ff00ff">&nbsp;قريبا&nbsp;</font> ● · مبدع الحائط لهذا الأسبوع · ● <font class="iraq11" color="#5CAD9A">&nbsp; قـريبا &nbsp;</font> ● · مبدعة الحائط لهذا الأسبوع · ● <font class="iraq11" color="#800000">&nbsp; قريبا &nbsp;</font> ● · ‫أفضل تواجد لهذا الأسبوع · ● <font class="iraq11" color="#417570">&nbsp;قريبا &nbsp;</font> ● · مع تمنياتنا للجميع بـ أطيب الاوقات&nbsp;</marquee></div><center>'}`)['insertBefore']('div#tlogins .lonline.light.break');
$('.ae.label.label-primary.fa.fa-gear')['html'](`${'⠀'}`);
$('label.ae.fa.label.label-primary.fa-commenting-o')['html'](`${'⠀'}`);
$('.ae.fa.label.label-primary.fa-users')['html'](`${'⠀'}`);
$('.hand.nosel.fl.uzr.border')['css']({
    margin: '1px 0'
    , borderRadius: '0px'
}), $('.checkbox label')['html'](`${'<input id="stealth"type="checkbox"value=""><i class="fa fa-eye-slash"aria-hidden="true"style="margin-top: 3px"></i>'}`);
$('textarea#tbox')['on']('paste', function (_0x9cd6x1) {
    _0x9cd6x1['preventDefault']()
});
$('div#l1 button.btn.btn-primary')['bind']('click', function () {
    alert('اهلا وسهلا بكم في شات  آحبـك :heart: سجل عضوية تحصل على 5000 لايك وزخرفة :: طريقة التسجيل اضغط على خيار (تسجيل) اكتب (اكتب اسمك المستعار + كلمة المرور ) وبعدها اضغط دخول')
});
$(`${'<style>.hand.corner{background-color:#000!important;border:2px solid #c12e2a!important;color:#f0ad4e;border-radius:0;text-align:center;border-style:solid;border-right:7px solid!important;border-left:7px solid!important;border-color:#2ea1ad;border-left-style:double!important;border-right-style:double!important}div.break.fl::before{content:" اخي الزائر اختي الزائرة اذا واجهت مشكله في دخول الشات يرجى مراسلتنا من صفحة اتصل بنا :email: .. ";color:#0f0!important;font-family:\'jazeera\',FontAwesome;font-size:16px}.break.fl{text-align:center;padding:5px!important;font-family:\'jazeera\',FontAwesome;color:red;-webkit-animation:mymove .5s infinite;animation:mymove .5s infinite}</style>'}`)['insertBefore']('div#tlogins .lonline.light.break');
$('div#tlogins button.btn.btn-primary')['click'](function () {
    var _0x9cd6x2 = setInterval(function () {
        var _0x9cd6x3 = $('.pmsgc')['length'];
        0 < _0x9cd6x3 ? ($(`${' <center><form name="jump"><div class="des"><map id="ColorsMap" name="ColorsMap"><area alt="" coords="275, 0, 298, 25" href="javascript:chooseStyle(\'none\',60)" shape="rect"title="1" style="left: 0px;padding: 3px 98px 5px 14px !important;"><area alt="" coords="244, 0, 268, 25" href="javascript:chooseStyle(\'Co2\',60)" shape="rect" title="2" style="left: 0px;padding: 0px 0px 0px 34px !important;"><area alt="" coords="213, 0, 238, 25" href="javascript:chooseStyle(\'Co3\',60)" shape="rect" title="3"style="left: 0px;padding: 0px 0px 0px 32px !important;"><area alt="" coords="183, 0, 207, 25" href="javascript:chooseStyle(\'Co4\',60)" shape="rect" title="4"style="left: 0px;padding: 0px 0px 0px 21px !important;"><area alt="" coords="152, 0, 177, 25"href="javascript:chooseStyle(\'Co5\',60)" shape="rect" title="5" style="left: 0px;padding: 0px 0px 0px 37px !important;"></map><img alt="" height="25"src="https://1.top4top.net/p_1388gqx1c1.gif"width="300" usemap="#ColorsMap"></div</form><img id="me1" border="0" style="width: 100%;" src="sico/z1f1vh9i8110.png" onclick="document.getElementById(\'me2\') .style.display=\'block\'">'}`)['appendTo']('#settings'), clearInterval(_0x9cd6x2)) : console['log'](_0x9cd6x3)
    }, 1)
})
